[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler and remappings
solc_version = "0.8.24"
auto_detect_remappings = false
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@octant-oz/=lib/octant-v2-strategy-foundry-mix/lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",

]

# Optimizer settings
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
