[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler and remappings
solc_version = "0.8.26"
auto_detect_remappings = false
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@octant-core/=lib/octant-v2-core/src/",
]

# Optimizer settings
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
